# Generated by Django 5.2 on 2025-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
